Fixed SyntaxError: Cannot use import statement outside a module
Error messages when `npm run test` :

```sh
 FAIL  src/App.test.js
  ● Test suite failed to run

    /app/node_modules/nanoid/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { randomFillSync } from 'crypto'
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import * as React from 'react';
      2 | import { Button } from '@mui/material';
    > 3 | import { nanoid } from 'nanoid'
        | ^
      4 | import { connect } from 'react-redux'
...
```

By adding command below in `package.json` :

```json
{
  "scripts": {
    ...,
    "test": "react-scripts test --transformIgnorePatterns 'node_modules/(?!@codemirror)/'"
  }
}
```